### ISSUE TITLE
File overwrite warning not implemented in `annotate_img`

### ISSUE THREAD

**Issue by pdeperio** [WatChPhoto/pmt-annotation#27]
Seems `.txt` and `.png` are automatically overwritten now without prompting.

**Comment by msekatchev** [comment]
were you trying to use `annotate_img()`?
I didn't implement the warning inside `annotate_img()`, only for `annotate_dir()` when copying the text and mask to a directory.

**Comment by msekatchev** [comment]
I can add a warning to annotate_img too

**Comment by pdeperio** [comment]
ah yes, was using `annotate_img()`.

technically, this functionality should be in `annotate_img()` (since `annotate_dir` should just be a loop over files without redundant code).

And even a separate `save` function that can be applied to multiple files (again to minimize copy/pasted code).

**Comment by msekatchev** [comment]
Added `save_function` branch to address this issue and #26, but I want to test the code a bit more before making a PR.
