### ISSUE TITLE
Check input ordering of images

### ISSUE THREAD

**Issue by pdeperio** [WatChPhoto/pmt-annotation#3]
Images seem to get loaded in a different order than they are in the directory using `ls`. Would be good to keep same order since they're basically chronological on disk.

**Comment by msekatchev** [comment]
What is the order you are getting with ls? It looks like it's reading them in alphabetical/incrementing order.

**Comment by pdeperio** [comment]
Here's the output of my `ls`
```
B2360334.JPG  B2370344.JPG  B2380354.JPG  B2390365.JPG  B2400374.JPG
```
and of `annotate_dir`:
```
['B2380354.JPG', 'B2390365.JPG', 'B2360334.JPG', 'B2370344.JPG', 'B2400374.JPG']
```
